In [1]:
list = [[2,7,6],[9,5,1],[4,3,8]]
for row in list: print(row)

[2, 7, 6]
[9, 5, 1]
[4, 3, 8]


In [2]:
import numpy as np
arr = np.array(list)
print(arr)

[[2 7 6]
 [9 5 1]
 [4 3 8]]


In [3]:
print(list[1][2])

1


In [4]:
print(arr[:,2])

[6 1 8]


In [6]:
print([list[i][i] for i in range(len(list))])

[2, 5, 8]


In [7]:
print(arr.diagonal())

[2 5 8]


In [10]:
arr1 = np.fliplr(arr)
print(arr1)

[[6 7 2]
 [1 5 9]
 [8 3 4]]


In [11]:
print(np.fliplr(arr).diagonal())

[6 5 4]


In [17]:
numbers = [1,2,3,4,5,6,7,8,9]
def is_prime(n):
    for i in range(2,n//2):
        if n == 1 or n == 2:
            return False
        if n%i == 0:
            return False
    return True
primes = [i for i in numbers if is_prime(i)]
print(primes)

[1, 2, 3, 4, 5, 7]


In [19]:
L = ['A', 'C', 'T', 'G']
s = ''.join(L)
s1= ' '.join(L)
print(s)
print(s1)

ACTG
A C T G
